heroes/urls.py
from django.urls import path
from heroes.views import lista_heroes, get_heroe

urlpatterns = [
    path('', lista_heroes, name="heroes"),
    path('<int:id>/', get_heroe, name="heroe")
]

super_heroes/urls.py
from django.contrib import admin
from django.urls import path, include
from heroes.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', inicio, name="inicio"),
    path('heroes/', include('heroes.urls')),
]

heroes/models.py
from django.db import models

# Create your models here.
class superHeroes(models.Model):
    nombre = models.CharField(max_length=128)
    fecha_nacimiento = models.DateField()
    peso_kg = models.IntegerField()
    
    def __str__(self):
        return f"{self.nombre}"

class Poder(models.Model):
    nombre = models.CharField(max_length=128)
    super_heroes = models.ForeignKey('superHeroes',on_delete=models.CASCADE,null=True)

    def __str__(self):
        return f"{self.nombre} - {self.super_heroes}"

heroes/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template, Context, loader
from heroes.models import superHeroes

def inicio(request):
    return render(request, "heroes/inicio.html")

def lista_heroes(request):
    queryset = superHeroes.objects.all()
    diccionario = {'heroes':queryset}
    plantilla = loader.get_template('heroes/heroes_list.html')
    documento_html = plantilla.render(diccionario)
    
    return HttpResponse(documento_html)

def get_heroe(request, id):
    heroe = superHeroes.objects.get(id=id)
    diccionario = {'heroe':heroe}
    plantilla = loader.get_template('heroes/heroe.html')
    documento_html = plantilla.render(diccionario)
    
    return HttpResponse(documento_html)

heroes/templates/heroes/heroe.html
{% extends 'heroes/plantilla_base.html' %}

{% block contenido_base %}

<h3>Nombre: {{heroe.nombre}}</h3>
<h3>Peso: {{heroe.peso_kg}}</h3>
<h4>Lista de Poderes</h4> 
{% for poder in heroe.poder_set.all%} 
<span>{{poder.nombre}}<br></span>
{% endfor%} 

{% endblock contenido_base %}

heroes/templates/heroes/heroes_list.html
{% extends 'heroes/plantilla_base.html' %}

{% block contenido_base %}


Lista de Super Heroes
{% for heroe in heroes%} 
<p><a href="{% url 'heroe' heroe.id %}">{{heroe.nombre}}</a></p>
{% endfor%} 

{% endblock contenido_base %}

heroes/templates/heroes/inicio.html
{% extends 'heroes/plantilla_base.html' %}

{% block contenido_base %}

Bienvenidos a la academia de Super Heroes

{% endblock contenido_base %}

heroes/templates/heroes/plantilla_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Inicio</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'heroes/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'heroes/css/styles.css' %}" rel="stylesheet" />

    </head>

    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'heroes' %}">Heroes</a>
            </div>
        </nav>


        {% block contenido_base %}
        {% endblock contenido_base %}


        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">Ayuda</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contacto</a></li>
                      
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Curso de Python - CoderHouse.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href=""><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'heroes/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

    </body>
</html>